// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://tsfswvmwkfairaoccfqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRzZnN3dm13a2ZhaXJhb2NjZnFhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU3NDI3NjYsImV4cCI6MjA4MTMxODc2Nn0.BSXKdrmK3_nYg4jsGe_Q15XKHCNtb0X6_tAAJovchOQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);